name: "Checkov Validate & Terrafom Validate"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      run: python3 -m venv venv

    - name: Install Checkov
      run: pip3 install checkov 

    - name: Check Terraform with Checkov
      run: |
        checkov -f main.tf --quiet -o json --output-file-path checkov_result/ 
        
    - name: Check Terraform with Checkov Success
      run: echo "Checkov completed successfully."

    - name: Send Failure Notification
      if: failure()
      run: echo "The 'build' job failed."

  
    
  terraform-job2:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3   # Specify the desired Terraform version

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt

      - name: Output File Push
        run: |
           echo "Creating output file"
           git checkout -b output
           git branch 
           ls
           
           git config --global user.email "nsmgbros001@gmail.com"
           git config --global user.name "Santhosh-Nagarajan"
           
           rm -r *.tf terraform.tfvars .terraform .github/ .terraform.lock.hcl
           touch demo.txt
           
           git add .
           git commit -m "create output file"
           git remote set-url origin https://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@github.com/Santhosh-Nagarajan/githubaction-used-checkov.git 
           git remote -v
           git push -u origin output
