name: Checkov and Terraform

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Checkov
        run: pip3 install checkov 

      - name: Check Terraform with Checkov
        run: |
            checkov -f main.tf --quiet -o json --output-file-path checkov_result/ 
        
      - name: Check Terraform with Checkov Success
        run: echo "Checkov completed successfully."

      - name: Send Failure Notification
        if: failure()
        run: echo "The 'build' job failed."
       
      
                      
 

  terraform-job2:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3   # Specify the desired Terraform version

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt

      - name: Output File Push
        run: |
           git checkout -b output
           git branch
           ls
           git config --global user.email "nsmgbros001@gmail.com"
           git config --global user.name "Santhosh-Nagarajan"
           rm -r *.tf terraform.tfvars .terraform  
           touch out.txt
           git add .
           git commit -m "create output file"
           git remote set-url origin https://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@github.com/Santhosh-Nagarajan/githubaction-used-checkov.git
           git remote -v
           git push -u origin output
        
        env:
            GH_TOKEN: ${{ secrets.YOUR_SECRET_NAME }}

     
      
