name: 'Checkov Validation And Terraform Deploy To GCP'

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Python Version
        run: python3 --version

      - name: Install Checkov
        run: pip3 install checkov 

      - name: Check Terraform with Checkov
        run: checkov -f main.tf --quiet -o json --output-file-path checkov_result/ 
        
      - name: Check Terraform with Checkov Success
        run: echo "Checkov completed successfully."

      - name: Send Failure Notification
        if: failure()
        run: echo "The 'build' job failed."
       
      
                      
 

  terraform-job2:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6   # Specify the desired Terraform version

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt

         
      - name: Terraform Validation
        run: terraform validate

         
      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply 
      #   run: terraform apply --auto-approve | awk '/^Outputs:/{outputFound=1; output=""; count=0} outputFound{output=output $0 ORS; count++} count==4{print output > "output.txt"; exit}'
      # #run: terraform apply --auto-approve -var="project-id=${{ secrets.PROJECT_ID }}" -var="credentials=${{ secrets.CREDENTIAL }}" 


      - name: out
        run: touch output.txt
        
      - name: Echo
        run: |
          echo "${{ secrets.PROJECT_ID }}"
          echo "${{ secrets.CREDENTIAL}}"

      - name: Check for output.txt
        id: check-output-file
        run: |
         if [ -f "output.txt" ]; then
          echo "Output.txt exists."
          echo "::set-output name=file-exists::true"
         else
          echo "Output.txt does not exist."
          echo "::set-output name=file-exists::false"
         fi

      - name: Conditional Steps
        if: steps.check-output-file.outputs.file-exists == 'true'
        run: |
              echo "Executing steps since output.txt exists."
              echo "Creating GCP Output File"
              
              git push origin --delete output || git branch --all 
              git checkout -b output || git branch

              ls

              git config --global user.email "nsmgbros001@gmail.com"
              git config --global user.name "Santhosh-Nagarajan"

              rm -r *.tf terraform.tfvars .terraform .github/ nee.txt
              

              git add .
              git commit -m "create output file"
              
              git remote set-url origin https://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@github.com/Santhosh-Nagarajan/githubaction-used-checkov.git
              git remote -v
              
              git push -u origin output      
        # Add your additional steps here, for example:
        # run: echo "Do something when output.txt exists."

      # - name: Output File Push
      #   run: |
      #         echo "Creating GCP Output File"
              
      #         git push origin --delete output || git branch --all 
      #         git checkout -b output || git branch

      #         ls

      #         git config --global user.email "nsmgbros001@gmail.com"
      #         git config --global user.name "Santhosh-Nagarajan"

      #         rm -r *.tf terraform.tfvars .terraform .github/ .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup
              

      #         git add .
      #         git commit -m "create output file"
              
      #         git remote set-url origin https://${{ secrets.DOCKERHUB_TOKEN }}@github.com/Santhosh-Nagarajan/githubaction-used-checkov.git
      #         git remote -v
              
      #         git push -u origin output      
